export class PlanetWeatherDto {
  id: string;
  timestamp?: number;
  location?: string;
  temperature?: number;
  humidity?: number;
  planet_name?: string;
  planet_climate?: string;
  match_score?: number;
  autogenerated?: number | boolean;

  constructor(data?: Partial<PlanetWeatherDto>) {
    if (data) {
      this.id = data.id || '';
      this.timestamp = data.timestamp;
      this.location = data.location;
      this.temperature = data.temperature;
      this.humidity = data.humidity;
      this.planet_name = data.planet_name;
      this.planet_climate = data.planet_climate;
      this.match_score = data.match_score;
      this.autogenerated = data.autogenerated;
    }
  }
}