import { Injectable } from '@nestjs/common';
import { PlanetWeatherService } from '../../infrastructure/services/planet-weather.service';
import { PlanetWeatherDto } from '../dto/planet-weather.dto';
import { PlanetWeatherListDto } from '../dto/planet-weather-list.dto';

@Injectable()
export class GetAllPlanetWeatherUseCase {
  constructor(private readonly planetWeatherService: PlanetWeatherService) {}

  async execute(autogenerated: boolean, limit: number, lastKey?: string): Promise<PlanetWeatherListDto> {
    const { items, lastKey: newLastKey, lastKeyString } = await this.planetWeatherService.getAllPlanetWeather(autogenerated, limit, lastKey);
    console.log(newLastKey);
    return {
      items: items.map(item => new PlanetWeatherDto(item)),
      lastKey: newLastKey,
      lastKeyString: lastKeyString
    };
  }
}